parameters:
  dbxdeploy:
    databricks:
      host: 'https://dbc-123.cloud.databricks.com'
      token: 'abcd123456'
      clusterId: '0416-084917-doles835'
    source:
      notebooks:
        baseDir: 'src/foobar'
